// Event configuration — edit these values as needed
// PHONES: first entry is primary (used in Footer)
// INVITATION_URL: set PUBLIC_INVITATION_URL in .env for production

export const EVENT_DATE = new Date("2026-09-19T17:30:00+02:00");

export const EVENT_TIME = "17:30";

export const EVENT_DATE_ISO = "2026-09-19";

export const ADDRESS = "D'Locosparty, Granada";

// Full embed URL generated by Google Maps "Compartir → Insertar un mapa".
// Contains the legacy Place ID (`0xd71ff7ef3b8530f:0x85b5c1d822f29974`) plus
// hardcoded coordinates, so it always resolves to the exact pin.
export const GOOGLE_MAPS_EMBED_URL =
  "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3177.0720553371984!2d-3.6960900241422303!3d37.22226437212981!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd71ff7ef3b8530f%3A0x85b5c1d822f29974!2sD%E2%80%99locosparty%20Parque%20de%20bolas%20en%20Granada!5e0!3m2!1ses-419!2ses!4v1788263688352!5m2!1ses-419!2ses";

// Link used for the "open in Maps" overlay — points to the exact place + coords
export const GOOGLE_MAPS_URL =
  "https://www.google.com/maps/place/D%E2%80%99locosparty+Parque+de+bolas+en+Granada/@37.2222644,-3.6960917,17z";

export const PHONES: { label: string; number: string }[] = [
  { label: "Mamá", number: "+34630173975" },
];

// Static URL used in Google Calendar details field
// In production set PUBLIC_INVITATION_URL env var
export const INVITATION_URL =
  import.meta.env.PUBLIC_INVITATION_URL || "https://tu-invitacion.netlify.app";

// Event duration in hours (start → end in Google Calendar)
export const EVENT_DURATION_HOURS = 2;

// Time zone identifier (IANA) used for the Google Calendar event
export const EVENT_TIMEZONE = "Europe/Madrid";
